# Copy this to config.toml

admins = ["YOUR_USERNAME"]
api_token = "YOUR_TOKEN"
log_file = "/var/log/stickerdome/stickerdome.log"
webhook_port = 9001
webhook_url = "https://example.com/SOMETHING_RANDOM"

downtime_notifications = true

redis_db = 15
redis_socket = "/run/redis/redis.sock"

max_submissions = 10
min_votes = 5

[debug]
enabled = false
autovote_until = 250
disable_bracket = true
match_duration = 2
