# Copy this to config.toml

admins = ["YOUR_USERNAME"]
api_token = "YOUR_TOKEN"
log_file = "/var/log/stickerdome/stickerdome.log"
webhook_port = 9001
webhook_url = "https://example.com/SOMETHING_RANDOM"

redis_db = 15
redis_socket = "/run/redis/redis.sock"

max_submissions = 10
