[animation]
allowed_mime_types = ["video/mp4"]
max_duration_secs = 60
max_size_bytes = 10485760
save_dir = "/home/gifdome/animations"
temp_filename_bits = 128
temp_save_dir = "/home/gifdome/temp"
thumbnail_fingerprint_file = "/home/gifdome/fingerprints.db"
thumbnail_fingerprint_threshold = "95%"
thumbnail_save_dir = "/home/gifdome/thumbnails"
vspipe_working_dir = "/home/gifdome/gifdome/bot/combine"

[bot]
token = ""  # required

[db]
dbname = "gifdome"
application_name = "gifdome"
user = "gifdome"
password = ""

[dev]
debug = false
testing = false

[dev.init_db]
dbname = "gifdome"
application_name = "gifdome"
user = "gifdome"
password = ""

[poll]
option_a_text = "\U0001F170"
option_b_text = "\U0001F171"

[scheduler]
job_interval_secs = 20
job_timeout_secs = 20
poll_interval_millis = 500

[server]
socket_path = "/tmp/gifdome-www.sock"
socket_permissions = 0o775

[tournament]
id_bits = 128
max_rounds = 12
round_lengths_secs = [
    43200,
    28800,
    14400,
    7200,
    3600,
    1800,
    600,
    300,
    300,
    300,
    300,
    300,
]

[webhook]
secret = ""  # required
socket_path = "/tmp/gifdome-webhook.sock"
socket_permissions = 0o775
url = ""  # required
